### ISSUE TITLE
Fatal error after running the compiled exe.

### ISSUE THREAD

**Issue by alpinian** [HusseinBakri/Tanit-Keylogger#1]
Hello, I have been working on setting this up recently. I edited main.py, changed the # to block the import keylogger.py command and un commented the "import keylogger_persistance_windows" command. I then left time at 120, edited my email and password info then saved and exited. I deleted "keylogger.py" because I used windows persistence then ran ran pyinstaller (I tried having all three .pys before but same error occurred). I got 'main.exe' in the dist folder like expected but when I run it I get a popup box that says "fatal error detected, failed to execute script main". I know this is not an error on my computer, but rather in the compile or the code before as I tested it on a friends pc also. If you happen to see this thanks so much : )

**Comment by alpinian** [comment]
Resolved that issue, Now I am getting several errors in the main code. 
![image](https://user-images.githubusercontent.com/70292986/91361528-82aae480-e7c6-11ea-93cd-f0b0c5d4e827.png)

did one of the imports not install?

**Comment by HusseinBakri** [comment]
Fixed a bug in keylogger_persistance_windows,  forgot to put "self" in front of add_registry(). 
Maybe this would solve the problem. I wrote this tool 2 years ago so I am not maintaining it anymore. Any help in this regards is greately appreciated since this repository is a bit famous with a lot of folks using it to learn how to create a keylogger in Python. But apparently pyinstaller is causing problems when transforming the python files to exe especially with the email feature so maybe it is a good idea first to check that everything works perfectly python-wise (of course turn off the antivirus) then use other tools that create executables. There are tools such Auto-py-to-exe. Kindly tell me what happens so I can edit the code or choose another tool for packaging.. Thx for using Tanit Keylogger
