### ISSUE TITLE
Not working after converting into exe

### ISSUE THREAD

**Issue by avi7611** [HusseinBakri/Tanit-Keylogger#2]
i have a full working python key logger which sends mail when ran using python, but when i converted it into exe it's no longer sending mails.

**Comment by HusseinBakri** [comment]
Hi There! Sorry for the later reply. 

I wrote this code from over 2 years ago so I am not maintaining the repository anymore. Any help in this regard is greatly appreciated for the benefit of all ethical hackers & security specialists out there!
 
It seems the problem is with pyinstaller, try other Python tools that create executables.

I think your problem is similar to this:
https://stackoverflow.com/questions/57239618/codekeylogger-converted-into-exe-with-pyinstaller-not-working-as-it-was

Kindly tell me what happens if you use another tool such Auto-py-to-exe or anything else.
