### ISSUE TITLE
Found and fixed the error in keylogger.py but there is another error in peristance keylogger

### ISSUE THREAD

**Issue by braptastic** [HusseinBakri/Tanit-Keylogger#4]
I have gotten the normal keylogger to work perfectly, the thing I was missing was "allow from less secure apps." 
![image](https://user-images.githubusercontent.com/71980898/94370178-639cbc80-00bc-11eb-8b42-dade3eac7f40.png)
it MUST be turned to on or you will get errors out the ass, now that is fixed and the program is working  fine, however when I switch over to the persistance keylogger I am getting a few errors as shows in the pic below. In line 20 I changed keylogger.Keylogger(120, "email" "pass) to keylogger_persistance_windows.Keylogger(interval email pass).  Otherwise it will result in a not defined because you are importing the wrong file. But after I do that I still get these errors screenshotted in the last pic. Thanks for helping and making this public, I love it so far  just this one error remains.
![image](https://user-images.githubusercontent.com/71980898/94370155-41a33a00-00bc-11eb-834c-71c676490083.png)

**Comment by braptastic** [comment]
Update: I have fixed the issue by adding two modules 

import sys
import subprocess

this fixes it so far, lmk if this is a temporary fix or something. thanks

**Comment by HusseinBakri** [comment]
Apologies yes you are right, I have added the two missing modules. 
Thx also for reminding me to add to the documentation that access to less secure apps should be enabled from the email provider settings.
 I totally forget to include that in the documentation since when I developed the tool back in 2018 I guess I had a dummy Gmail account that I had enabled this setting to work with all my python tools.
Thx again
